services:
  db:
    image: postgres:15
    container_name: taskdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: task-scheduler
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tasks
      DB_PORT: "5432"
      APP_PORT: "8080"
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata:
